---
- hosts: fpm-multi-host
  become: true

  vars:
    host_sshd_user: 'vagrant'
    host_ioc_release_version: '10.2-RELEASE'
    syslogd_server: 10.1.0.3
    ssmtp_root: 'freebsd-ansible-demo'
    ssmtp_rewrite_domain: 'maildrop.cc'
    ssmtp_mailhub: 'mail.maildrop.cc'
    ssmtp_auth_user: 'mail.maildrop.cc'
    ssmtp_auth_pass: 'mail.maildrop.cc'
    mariadb_root_passwd: 'password'

  roles:
    - { role: JoergFiedler.freebsd-jailed-syslogd,
        tags: ['_syslogd'],
        use_ssmtp: true,
        jail_name: 'syslogd',
        jail_net_ip: '{{ syslogd_server }}' }
    - { role: JoergFiedler.freebsd-jailed-sshd,
        tags: ['_sshd'],
        use_ssmtp: true,
        use_syslogd_server: true,
        jail_name: 'sshd',
        jail_net_ip: '10.1.0.2' }
    - { role: JoergFiedler.freebsd-jailed-mariadb,
        tags: ['_mariadb'],
        jail_name: 'mariadb',
        jail_net_ip: '10.1.0.4' }
    - { role: JoergFiedler.freebsd-jailed-nginx,
        tags: ['_nginx'],
        jail_name: 'nginx',
        jail_net_ip: '10.1.0.3',
        nginx_servers: [
        { default: true,
          name: 'joomla.localhost',
          aliases: 'default.localhost',
          proxy: { host: '10.1.0.5' } },
        { default: false,
          name: 'wordpress.localhost',
          aliases: 'non-default.localhost',
          proxy: { host: '10.1.0.6' } }
        ]
      }
    - { role: JoergFiedler.freebsd-jailed-joomla,
        tags: ['_joomla'],
        joomla_db_host: '10.1.0.4',
        joomla_db_host_user: 'root',
        joomla_db_host_password: '{{ mariadb_root_passwd }}',
        joomla_sftp_port: 10200,
        nginx_pf_rdrs: [],
        jail_name: 'joomla',
        jail_net_ip: '10.1.0.5' }
    - { role: JoergFiedler.freebsd-jailed-wordpress,
        tags: ['_wp'],
        wp_db_host: '10.1.0.4',
        wp_db_host_user: 'root',
        wp_db_host_password: '{{ mariadb_root_passwd }}',
        wp_sftp_port: 10201,
        nginx_pf_rdrs: [],
        jail_name: 'wordpress',
        jail_net_ip: '10.1.0.6' }
