---
- name: Check if zpool is configured for iocage
  command: /sbin/zpool get comment {{ iocage_zpool }}
  changed_when: false
  register: zpool_comment

- name: Check if release {{ iocage_release_version}} is fetched
  stat:
    path: '{{ iocage_releases_dir }}/{{ iocage_release_version }}'
    get_md5: no
  register: release_dir

- name: Mark zpool for iocage usage
  command: /sbin/zpool set comment=iocage {{ iocage_zpool }}
  when: zpool_comment.stdout | search("tank.*comment.*-")

- name: Install iocage
  pkgng:
    name: iocage
    state: present

- name: Fetch FreeBSD release {{ iocage_release_version }}
  shell: /usr/local/sbin/iocage fetch release="{{ iocage_release_version }}" ftpfiles="base.txz src.txz doc.txz"
  when: release_dir.stat.isdir is undefined

- name: Enable iocage service
  service:
    name: iocage
    enabled: true
