---
- name: Ensure ZFS is started
  service: name=zfs
           enabled=yes
           state=started

- name: Check if ZFS pool exists
  command: zpool status {{ iocage_zpool }}
  register: zpool_status
  ignore_errors: yes
  changed_when: false

- name: Create ZFS pool
  command: zpool create {{ iocage_zpool }} {{ iocage_zpool_devs }}
  when: "'no such pool' in zpool_status.stderr"
