language: python
python: '2.7'
sudo: false

install:
- pip install ansible==2.0.1
- pip install netaddr

before_script:
- wget https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb
- dpkg -x vagrant_1.8.1_x86_64.deb /tmp/vagrant
- export PATH=${PATH}:/tmp/vagrant/opt/vagrant/bin
- vagrant plugin install vagrant-aws

script:
- vagrant box add https://rawgit.com/JoergFiedler/freebsd-box/master/metadata.json --provider aws
- vagrant up --provider aws
- btsync_host=$(vagrant ssh-config btsync |grep HostName |awk '{print $2}')
- http_status=$(curl -u admin:admin https://${btsync_host}:20202/gui/ --insecure -w %{http_code} -o /dev/null -s)
- [[ $http_status -eq 200 ]]
- vagrant destroy -f

env:
  global:
    - secure: a6djzDXyErLludVb1xVaIk63gTw4AjqFBW0JMeofjF2L0MScASnkyKEPL7gzyrP6YWWUT0VlTxkMZfDx/lAYUh3uuZRkJnW/txoxJu0E6/jWYcGOZiODw1rXqsJObekXcjZ+/kGy9Fxs9AqkgzW52SQVUJOAnZsI6fzgNTjQ+i4=
    - secure: Y554K7VMIMD7jqeEyB6YVq2ZXZmy2s5sh04GoXJb6hJlANdqPtK6BjQlIh6VNtFF6F65MDji+fo0rU1k4MnRx9N7/OjNTFg8QpWv0xX2YM3+PQN9b53Shys5xHQek6w6RgQCSU3UQ7dVS9qTwZbwuz1ra/o/9k1ntlzukgFs4Zc=
