---
language: python
python: "2.7"
sudo: false

addons:
  apt:
    packages:
    - vagrant
    - python-pip

install:
  - vagrant plugin install vagrant-aws
  - pip install ansible

script:
  - "$(which true)"
