---
- hosts: default
  sudo: true

  vars:
    host_sshd_user: 'vagrant'
    host_ioc_release_version: '10.2-RELEASE'
    syslogd_server: 10.1.0.3
    ssmtp_forward_address: 'freebsd-ansible-demo@maildrop.cc'
    ssmtp_forward_mailhub: 'mail.maildrop.cc'

  roles:
  - { role: JoergFiedler.freebsd-jailed-syslogd,
      tags: ['syslogd'],
      use_ssmtp: true,
      jail_name: 'syslogd',
      jail_net_ip: '{{ syslogd_server }}' }
  - { role: JoergFiedler.freebsd-jailed-sshd,
      tags: ['sshd'],
      use_ssmtp: true,
      use_syslogd_server: true,
      jail_name: 'sshd',
      jail_net_ip: '10.1.0.2' }
