---
- name: Copy {{ jail_name }} pf configuration (rdr rules)
  template:
    src: 'pf.anchor.rdr-jail.conf.j2'
    dest: '/etc/pf.anchor.rdr-jail.{{ jail_name }}.conf'
  notify:
    - reload pf

- name: Add {{ jail_name }} pf configuration to anchor.rdr-jail conf
  lineinfile:
    dest: '/etc/pf.anchor.rdr-jail.conf'
    state: present
    line: 'include \"/etc/pf.anchor.rdr-jail.{{ jail_name }}.conf\"'
  notify:
    - reload pf

- name: Copy {{ jail_name }} pf configuration (rls rules)
  template:
    src: 'pf.anchor.rls-jail.conf.j2'
    dest: '/etc/pf.anchor.rls-jail.{{ jail_name }}.conf'
  notify:
    - reload pf

- name: Add {{ jail_name }} pf configuration to anchor.rls-jail conf
  lineinfile:
    dest: '/etc/pf.anchor.rls-jail.conf'
    state: present
    line: 'include \"/etc/pf.anchor.rls-jail.{{ jail_name }}.conf\"'
  notify:
    - reload pf

- name: Add {{ jail_name }} to allowed NAT hosts
  lineinfile:
    dest: '/etc/pf.table.nat-jails'
    insertbefore: EOF
    line: '{{ jail_ip }}'
  notify:
    - reload pf

- name: Comment pf rule which allows sshd on external interface
  lineinfile:
    dest=/etc/pf.conf
    state=present
    regexp='^(pass quick.*to \$ext_ip port \$sshd_port.*)$'
    line='#\1'
    backrefs=yes
  notify:
    - reload pf
