---
- name: Find UUID for {{ jail_name }}
  shell: /usr/local/sbin/iocage show ip4_addr | grep {{ jail_ip }} | cut -d ' ' -f 1
  changed_when: false
  register: jail_uuid

- name: Create base jail {{ jail_name }}
  command: /usr/local/sbin/iocage create -b tag={{ jail_name }} ip4_addr={{ jail_ip_addr }}
  when: not jail_uuid.stdout
  register: jail_created
  notify:
    - Start all jails with boot=on

- name: Find UUID for {{ jail_name }}
  shell: /usr/local/sbin/iocage show ip4_addr | grep {{ jail_ip }} | cut -d ' ' -f 1
  changed_when: false
  register: jail_uuid

- name: Set jails {{ jail_name }} properties
  command: /usr/local/sbin/iocage set {{ item }} {{ jail_uuid.stdout }}
  with_items:
    - 'boot=on'
    - 'hostname={{ jail_hostname }}'
  when: jail_created|changed

- name: Register jail s home diretory
  command: echo {{ iocage_jails_dir }}/{{ jail_uuid.stdout }}/root
  changed_when: false
  register: jail_home

